FROM python:3.9

WORKDIR /app

# Встановлюємо все підряд, без кешування та оптимізацій
RUN pip install torch torchvision pillow

COPY model.pt .
COPY inference.py .

ENTRYPOINT ["python", "inference.py"]