apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  project: default
  source:
    chart: mlflow
    repoURL: https://community-charts.github.io/helm-charts
    targetRevision: 0.7.x
    helm:
      values: |
        backendStore:
          postgres:
            host: postgres-postgresql.default.svc.cluster.local
            database: mlflow
            user: postgres
            password: password123
        defaultArtifactRoot: s3://mlflow-artifacts/
        extraEnvVars:
          - name: AWS_ACCESS_KEY_ID
            value: "admin"
          - name: AWS_SECRET_ACCESS_KEY
            value: "password123"
          - name: MLFLOW_S3_ENDPOINT_URL
            value: "http://minio.default.svc.cluster.local:9000"
        service:
          type: ClusterIP
          port: 5000
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
